files:
  - source: /locales/en.json
    translation: /locales/%two_letters_code%.json
  - source: /locales/en.csv
    translation: /locales/%two_letters_code%.csv
    first_line_contains_header: false,
    scheme: identifier,source_or_translation,context,max_length